/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall AppleAPICInterruptController::MetaClass::MetaClass(AppleAPICInterruptController::MetaClass *__hidden this); // idb
__int64 __fastcall AppleAPICInterruptController::MetaClass::~MetaClass(AppleAPICInterruptController::MetaClass *__hidden this); // idb
__int64 __fastcall AppleAPICInterruptController::AppleAPICInterruptController(IOInterruptController *a1, const OSMetaClass *a2);
__int64 __fastcall AppleAPICInterruptController::AppleAPICInterruptController(IOInterruptController *a1, const OSMetaClass *a2);
__int64 __fastcall AppleAPICInterruptController::~AppleAPICInterruptController(AppleAPICInterruptController *__hidden this); // idb
__int64 __fastcall AppleAPICInterruptController::~AppleAPICInterruptController(AppleAPICInterruptController *__hidden this); // idb
void __fastcall AppleAPICInterruptController::~AppleAPICInterruptController(AppleAPICInterruptController *this);
__int64 __fastcall AppleAPICInterruptController::getMetaClass(AppleAPICInterruptController *__hidden this); // idb
__int64 __fastcall AppleAPICInterruptController::MetaClass::MetaClass(AppleAPICInterruptController::MetaClass *__hidden this); // idb
IOInterruptController *__fastcall AppleAPICInterruptController::MetaClass::alloc(AppleAPICInterruptController::MetaClass *this, unsigned __int64 a2);
__int64 __fastcall AppleAPICInterruptController::AppleAPICInterruptController(IOInterruptController *a1);
__int64 __fastcall AppleAPICInterruptController::AppleAPICInterruptController(IOInterruptController *a1);
char __fastcall AppleAPICInterruptController::start(AppleAPICInterruptController *this, IOService *a2);
int __fastcall AppleAPICInterruptController::resetVectorTable(AppleAPICInterruptController *this);
// int __usercall AppleAPICInterruptController::free@<eax>(AppleAPICInterruptController *this@<rdi>, __int64 a2@<rax>);
int __fastcall AppleAPICInterruptController::dumpRegisters(AppleAPICInterruptController *this);
int __fastcall AppleAPICInterruptController::writeVectorEntry(AppleAPICInterruptController *this, int a2);
int __fastcall AppleAPICInterruptController::writeVectorEntry(__int64 a1, int a2, unsigned __int64 a3);
signed __int64 __fastcall AppleAPICInterruptController::getInterruptType(AppleAPICInterruptController *this, IOService *a2, int a3, int *a4);
int __fastcall AppleAPICInterruptController::registerInterrupt(AppleAPICInterruptController *this, IOService *a2, unsigned int a3, void *a4, void (__cdecl *a5)(void *, void *, void *, int), void *a6);
int __fastcall AppleAPICInterruptController::initVector(AppleAPICInterruptController *this, int a2, __int64 a3);
char AppleAPICInterruptController::vectorCanBeShared();
__int64 __fastcall AppleAPICInterruptController::getInterruptHandlerAddress(AppleAPICInterruptController *__hidden this); // idb
int __fastcall AppleAPICInterruptController::disableVectorHard(__int64 a1, int a2);
int __fastcall AppleAPICInterruptController::enableVector(__int64 a1, int a2);
__int64 __fastcall AppleAPICInterruptController::handleInterrupt(AppleAPICInterruptController *this, void *a2, IOService *a3, unsigned int a4);
int __fastcall AppleAPICInterruptController::prepareForSleep(AppleAPICInterruptController *this);
int __fastcall AppleAPICInterruptController::prepareForDeepIdle(AppleAPICInterruptController *this, int a2);
int __fastcall AppleAPICInterruptController::resumeFromSleep(AppleAPICInterruptController *this);
__int64 __fastcall AppleAPICInterruptController::setVectorPhysicalDestination(AppleAPICInterruptController *this, int a2, unsigned int a3);
int __fastcall AppleAPICInterruptController::callPlatformFunction(AppleAPICInterruptController *this, const OSSymbol *a2, unsigned __int8 a3, void *a4, void *a5, void *a6);
__int64 __fastcall AppleAPICInterruptController::MetaClass::~MetaClass(AppleAPICInterruptController::MetaClass *__hidden this); // idb
__int64 `global constructor keyed to'_a();
__int64 `global destructor keyed to'_a();
int _start();
__int64 *OSKextGetCurrentIdentifier();
__int64 *OSKextGetCurrentVersionString();
__int64 OSKextGetCurrentLoadTag();
int _stop();
// int __fastcall IOFree(_QWORD, _QWORD); weak
// int __fastcall IOLockAlloc(_QWORD); weak
// int __cdecl IOLockFree(_QWORD); weak
// int __fastcall IOLog(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int __fastcall IOMalloc(_QWORD); weak
// int IOSimpleLockAlloc(void); weak
// int __cdecl IOSimpleLockFree(_QWORD); weak
// int __fastcall IOSimpleLockLock(_QWORD); weak
// int __fastcall IOSimpleLockUnlock(_QWORD); weak
// int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD); weak
// _QWORD __cdecl OSMetaClass::~OSMetaClass(OSMetaClass *__hidden this); idb
// int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD); weak
// _QWORD __cdecl IOMemoryDescriptor::withAddressRange(IOMemoryDescriptor *__hidden this, unsigned __int64, unsigned __int64, unsigned int, task *); idb
// _QWORD __cdecl IOInterruptController::IOInterruptController(IOInterruptController *__hidden this, const OSMetaClass *); idb
// _QWORD __cdecl IOInterruptController::~IOInterruptController(IOInterruptController *__hidden this); idb
// void __cdecl OSObject::operator delete(void *); idb
// _QWORD __cdecl OSObject::operator new(OSObject *__hidden this, unsigned __int64); idb
// int __fastcall OSSymbol::withString(_QWORD); weak
// _QWORD __cdecl OSSymbol::withCString(OSSymbol *__hidden this, const char *); idb
// _QWORD IOService::getPlatform(IOService *__hidden this); idb
// _QWORD OSMetaClass::instanceConstructed(OSMetaClass *__hidden this); idb
// void __cdecl bzero(void *, size_t);
// int __fastcall kprintf(_QWORD, _QWORD, _QWORD, _QWORD); weak
// int __fastcall ml_set_interrupts_enabled(_QWORD); weak
// void panic(const char *, ...);

//-------------------------------------------------------------------------
// Data declarations

section_64 stru_B8 =
{
  {
    '_',
    '_',
    'c',
    's',
    't',
    'r',
    'i',
    'n',
    'g',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0',
    '\0'
  },
  "__TEXT",
  7751uLL,
  435uLL,
  7751u,
  0u,
  0u,
  0u,
  2u,
  0u,
  0u,
  0u
}; // weak
_QWORD off_2000[3] = { 43168LL, 43288LL, 45008LL }; // weak
_QWORD off_2008[2] = { 43288LL, 45008LL }; // weak
__int64 off_2010 = 45008LL; // weak
__int64 (__fastcall *off_2050[2])(AppleAPICInterruptController *__hidden this) =
{
  &AppleAPICInterruptController::~AppleAPICInterruptController,
  &AppleAPICInterruptController::~AppleAPICInterruptController
}; // weak
__int64 (__fastcall *off_2960[2])(AppleAPICInterruptController::MetaClass *__hidden this) =
{
  &AppleAPICInterruptController::MetaClass::~MetaClass,
  &AppleAPICInterruptController::MetaClass::~MetaClass
}; // weak
__int64 kmod_info = 0LL; // weak
_QWORD AppleAPICInterruptController::gMetaClass; // weak
int (*_realmain)(void); // weak
int (*_antimain)(void); // weak


//----- (0000000000000F80) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::MetaClass::MetaClass(AppleAPICInterruptController::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleAPICInterruptController", off_2000[0], 240LL);
  result = (__int64)off_2960;
  *(_QWORD *)this = off_2960;
  return result;
}
// 2000: using guessed type _QWORD off_2000[3];
// 2960: using guessed type __int64 (__fastcall *off_2960[2])(AppleAPICInterruptController::MetaClass *__hidden this);
// A698: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000000FB2) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::MetaClass::~MetaClass(AppleAPICInterruptController::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000000FBC) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::AppleAPICInterruptController(IOInterruptController *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOInterruptController::IOInterruptController(a1, a2);
  result = (__int64)off_2050;
  *(_QWORD *)a1 = off_2050;
  return result;
}
// 2050: using guessed type __int64 (__fastcall *off_2050[2])(AppleAPICInterruptController *__hidden this);

//----- (0000000000000FDC) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::AppleAPICInterruptController(IOInterruptController *a1, const OSMetaClass *a2)
{
  __int64 result; // rax@1

  IOInterruptController::IOInterruptController(a1, a2);
  result = (__int64)off_2050;
  *(_QWORD *)a1 = off_2050;
  return result;
}
// 2050: using guessed type __int64 (__fastcall *off_2050[2])(AppleAPICInterruptController *__hidden this);

//----- (0000000000000FFC) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::~AppleAPICInterruptController(AppleAPICInterruptController *this)
{
  return IOInterruptController::~IOInterruptController(this);
}

//----- (0000000000001006) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::~AppleAPICInterruptController(AppleAPICInterruptController *this)
{
  return IOInterruptController::~IOInterruptController(this);
}

//----- (0000000000001010) ----------------------------------------------------
void __fastcall AppleAPICInterruptController::~AppleAPICInterruptController(AppleAPICInterruptController *this)
{
  IOInterruptController::~IOInterruptController(this);
  OSObject::operator delete((void *)this);
}

//----- (0000000000001032) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::getMetaClass(AppleAPICInterruptController *this)
{
  return (__int64)&AppleAPICInterruptController::gMetaClass;
}
// 2B00: using guessed type _QWORD AppleAPICInterruptController::gMetaClass;

//----- (0000000000001040) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::MetaClass::MetaClass(AppleAPICInterruptController::MetaClass *this)
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(this, "AppleAPICInterruptController", off_2000[0], 240LL);
  result = (__int64)off_2960;
  *(_QWORD *)this = off_2960;
  return result;
}
// 2000: using guessed type _QWORD off_2000[3];
// 2960: using guessed type __int64 (__fastcall *off_2960[2])(AppleAPICInterruptController::MetaClass *__hidden this);
// A698: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001072) ----------------------------------------------------
IOInterruptController *__fastcall AppleAPICInterruptController::MetaClass::alloc(AppleAPICInterruptController::MetaClass *this, unsigned __int64 a2)
{
  IOInterruptController *v2; // rbx@1

  v2 = (IOInterruptController *)OSObject::operator new((OSObject *)&stru_B8.reloff, a2);
  IOInterruptController::IOInterruptController(v2, (const OSMetaClass *)&AppleAPICInterruptController::gMetaClass);
  *(_QWORD *)v2 = off_2050;
  OSMetaClass::instanceConstructed((OSMetaClass *)&AppleAPICInterruptController::gMetaClass);
  return v2;
}
// B8: using guessed type section_64 stru_B8;
// 2050: using guessed type __int64 (__fastcall *off_2050[2])(AppleAPICInterruptController *__hidden this);
// 2B00: using guessed type _QWORD AppleAPICInterruptController::gMetaClass;

//----- (00000000000010B2) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::AppleAPICInterruptController(IOInterruptController *a1)
{
  IOInterruptController::IOInterruptController(a1, (const OSMetaClass *)&AppleAPICInterruptController::gMetaClass);
  *(_QWORD *)a1 = off_2050;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleAPICInterruptController::gMetaClass);
}
// 2050: using guessed type __int64 (__fastcall *off_2050[2])(AppleAPICInterruptController *__hidden this);
// 2B00: using guessed type _QWORD AppleAPICInterruptController::gMetaClass;

//----- (00000000000010E2) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::AppleAPICInterruptController(IOInterruptController *a1)
{
  IOInterruptController::IOInterruptController(a1, (const OSMetaClass *)&AppleAPICInterruptController::gMetaClass);
  *(_QWORD *)a1 = off_2050;
  return OSMetaClass::instanceConstructed((OSMetaClass *)&AppleAPICInterruptController::gMetaClass);
}
// 2050: using guessed type __int64 (__fastcall *off_2050[2])(AppleAPICInterruptController *__hidden this);
// 2B00: using guessed type _QWORD AppleAPICInterruptController::gMetaClass;

//----- (0000000000001112) ----------------------------------------------------
char __fastcall AppleAPICInterruptController::start(AppleAPICInterruptController *this, IOService *a2)
{
  AppleAPICInterruptController *v2; // r15@1
  __int64 v3; // rax@1
  __int64 v4; // rcx@1
  char result; // al@1
  __int64 v6; // rax@3
  __int64 v7; // r12@3
  __int64 v8; // rax@3
  __int64 v9; // rax@5
  __int64 v10; // rax@5
  __int64 v11; // r14@5
  __int64 v12; // rax@6
  __int64 v13; // rax@6
  __int64 v14; // rax@7
  __int64 v15; // rax@8
  __int64 v16; // rax@8
  IOMemoryDescriptor *v17; // rax@9
  task *v18; // r8@9
  __int64 v19; // rbx@9
  __int64 v20; // rax@10
  __int64 v21; // rdi@10
  __int64 v22; // rax@11
  int v23; // edi@11
  __int64 v24; // rdi@12
  void *v25; // rax@12
  void *v26; // rdi@13
  int v27; // eax@13
  signed __int64 v28; // r12@13
  int v29; // ebx@14
  __int64 v30; // rax@15
  __int64 v31; // rax@17
  __int64 v32; // rax@18

  v2 = this;
  *((_QWORD *)this + 20) = OSSymbol::withCString("HandleSleepWake", (const char *)a2);
  v3 = OSSymbol::withCString("SetVectorPhysicalDestination", (const char *)a2);
  v4 = v3;
  *((_QWORD *)this + 21) = v3;
  result = 0;
  if ( *((_QWORD *)this + 20) && v4 )
  {
    LODWORD(v6) = (*(int (__fastcall **)(IOService *, _QWORD))(*(_QWORD *)a2 + 696LL))(a2, "Base Vector Number");
    v7 = *(_QWORD *)off_2008[0];
    LODWORD(v8) = OSMetaClassBase::safeMetaCast(v6, *(_QWORD *)off_2008[0]);
    if ( v8 )
      *((_DWORD *)this + 50) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v8 + 328LL))(v8);
    LODWORD(v9) = (*(int (__fastcall **)(IOService *, _QWORD))(*(_QWORD *)a2 + 696LL))(a2, "InterruptControllerName");
    LODWORD(v10) = OSSymbol::withString(v9);
    v11 = v10;
    if ( v10 )
    {
      LODWORD(v12) = (*(int (__fastcall **)(IOService *, _QWORD))(*(_QWORD *)a2 + 696LL))(a2, "Destination APIC ID");
      LODWORD(v13) = OSMetaClassBase::safeMetaCast(v12, v7);
      if ( v13 )
      {
        *((_DWORD *)this + 55) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v13 + 328LL))(v13);
        LODWORD(v14) = IOSimpleLockAlloc();
        *((_QWORD *)this + 24) = v14;
        if ( v14 )
        {
          LODWORD(v15) = (*(int (__fastcall **)(IOService *, _QWORD))(*(_QWORD *)a2 + 696LL))(a2, "Physical Address");
          LODWORD(v16) = OSMetaClassBase::safeMetaCast(v15, v7);
          if ( v16 )
          {
            LODWORD(v17) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v16 + 336LL))(v16);
            v19 = IOMemoryDescriptor::withAddressRange(v17, 0x100uLL, 0x803uLL, 0, v18);
            if ( v19 )
            {
              (*(void (__fastcall **)(__int64, _QWORD))(*(_QWORD *)v19 + 496LL))(v19, 0LL);
              LODWORD(v20) = (*(int (__fastcall **)(__int64, signed __int64))(*(_QWORD *)v19 + 512LL))(v19, 256LL);
              *((_QWORD *)this + 22) = v20;
              (*(void (__fastcall **)(__int64))(*(_QWORD *)v19 + 40LL))(v19);
              v21 = *((_QWORD *)this + 22);
              if ( v21 )
              {
                LODWORD(v22) = (*(int (**)(void))(*(_QWORD *)v21 + 280LL))();
                *((_QWORD *)v2 + 23) = v22;
                *(_DWORD *)v22 = 0;
                *((_DWORD *)v2 + 56) = *(_DWORD *)(*((_QWORD *)v2 + 23) + 16LL);
                **((_DWORD **)v2 + 23) = 1;
                v23 = (unsigned __int8)(*(_DWORD *)(*((_QWORD *)v2 + 23) + 16LL) >> 16);
                *((_DWORD *)v2 + 54) = v23;
                if ( v23 != 255 )
                {
                  v24 = (unsigned int)(v23 + 1);
                  *((_DWORD *)v2 + 54) = v24;
                  LODWORD(v25) = IOMalloc(v24 << 6);
                  *((_QWORD *)v2 + 17) = v25;
                  if ( v25 )
                  {
                    v26 = v25;
                    bzero(v25, (signed __int64)*((_DWORD *)v2 + 54) << 6);
                    *((_QWORD *)v2 + 29) = ~*((_QWORD *)v2 + 17);
                    v27 = *((_DWORD *)v2 + 54);
                    v28 = 8LL;
                    if ( v27 <= 0 )
                    {
LABEL_17:
                      LODWORD(v31) = IOMalloc(8LL * v27);
                      *((_QWORD *)v2 + 26) = v31;
                      if ( v31 )
                      {
                        AppleAPICInterruptController::resetVectorTable(v2);
                        (*(void (__fastcall **)(AppleAPICInterruptController *, _QWORD, _QWORD, signed __int64))(*(_QWORD *)v2 + 640LL))(
                          v2,
                          "Base Vector Number",
                          *((_DWORD *)v2 + 50),
                          32LL);
                        (*(void (__fastcall **)(AppleAPICInterruptController *, _QWORD, _QWORD, signed __int64))(*(_QWORD *)v2 + 640LL))(
                          v2,
                          "Vector Count",
                          *((_DWORD *)v2 + 54),
                          32LL);
                        **((_DWORD **)v2 + 23) = 1;
                        IOLog(
                          "IOAPIC: Version 0x%02x Vectors %d:%d\n",
                          (unsigned __int8)*(_DWORD *)(*((_QWORD *)v2 + 23) + 16LL),
                          *((_DWORD *)v2 + 50),
                          (unsigned int)(*((_DWORD *)v2 + 50) + *((_DWORD *)v2 + 54) - 1));
                        v32 = IOService::getPlatform("IOAPIC: Version 0x%02x Vectors %d:%d\n");
                        (*(void (__fastcall **)(__int64, __int64, AppleAPICInterruptController *))(*(_QWORD *)v32
                                                                                                 + 2304LL))(
                          v32,
                          v11,
                          v2);
                        (*(void (__fastcall **)(__int64))(*(_QWORD *)v11 + 40LL))(v11);
                        (*(void (__fastcall **)(AppleAPICInterruptController *, _QWORD))(*(_QWORD *)v2 + 1456LL))(
                          v2,
                          0LL);
                        return 1;
                      }
                    }
                    else
                    {
                      v29 = 0;
                      while ( 1 )
                      {
                        LODWORD(v30) = IOLockAlloc(v26);
                        *(_QWORD *)(*((_QWORD *)v2 + 17) + v28) = v30;
                        if ( !v30 )
                          break;
                        v27 = *((_DWORD *)v2 + 54);
                        v28 += 64LL;
                        ++v29;
                        if ( v29 >= v27 )
                          goto LABEL_17;
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      (*(void (__fastcall **)(__int64))(*(_QWORD *)v11 + 40LL))(v11);
    }
    result = 0;
  }
  return result;
}
// 2008: using guessed type _QWORD off_2008[2];
// A618: using guessed type int __fastcall IOLockAlloc(_QWORD);
// A628: using guessed type int __fastcall IOLog(_QWORD, _QWORD, _QWORD, _QWORD);
// A630: using guessed type int __fastcall IOMalloc(_QWORD);
// A638: using guessed type int IOSimpleLockAlloc(void);
// A868: using guessed type int __fastcall OSMetaClassBase::safeMetaCast(_QWORD, _QWORD);
// A9B8: using guessed type int __fastcall OSSymbol::withString(_QWORD);

//----- (000000000000146A) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::resetVectorTable(AppleAPICInterruptController *this)
{
  __int64 v1; // rbx@2
  __int64 v2; // rax@3
  int result; // eax@3

  if ( *((_DWORD *)this + 54) > 0 )
  {
    v1 = 0LL;
    do
    {
      v2 = *((_QWORD *)this + 26);
      *(_DWORD *)(v2 + 8 * v1) = (unsigned __int8)(v1 + *((_DWORD *)this + 50)) | 0x10000;
      *(_DWORD *)(v2 + 8 * v1 + 4) = *((_DWORD *)this + 55) << 24;
      result = AppleAPICInterruptController::writeVectorEntry(this, v1++);
    }
    while ( (signed int)v1 < *((_DWORD *)this + 54) );
  }
  return result;
}

//----- (00000000000014C6) ----------------------------------------------------
int __usercall AppleAPICInterruptController::free@<eax>(AppleAPICInterruptController *this@<rdi>, __int64 a2@<rax>)
{
  AppleAPICInterruptController *v2; // r14@1
  __int64 v3; // rdi@1
  __int64 v4; // rdi@3
  int v5; // eax@8
  signed __int64 v6; // r15@8
  int v7; // ebx@9
  __int64 v8; // rdi@10
  __int64 v9; // rdi@14
  __int64 v10; // rdi@16
  __int64 v11; // rdi@18
  __int64 v13; // [sp-8h] [bp-20h]@1

  v13 = a2;
  v2 = this;
  v3 = *((_QWORD *)this + 20);
  if ( v3 )
  {
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v3 + 40LL))(v3);
    *((_QWORD *)v2 + 20) = 0LL;
  }
  v4 = *((_QWORD *)v2 + 21);
  if ( v4 )
  {
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v4 + 40LL))(v4);
    *((_QWORD *)v2 + 21) = 0LL;
  }
  if ( *((_QWORD *)v2 + 17) )
  {
    if ( *((_QWORD *)v2 + 26) )
      panic("\"AppleAPIC::free()\\n\"@/SourceCache/AppleAPIC/AppleAPIC-17/AppleAPIC.cpp:258", v13);
    v5 = *((_DWORD *)v2 + 54);
    v6 = 8LL;
    if ( v5 > 0 )
    {
      v7 = 0;
      do
      {
        v8 = *(_QWORD *)(*((_QWORD *)v2 + 17) + v6);
        if ( v8 )
        {
          IOLockFree(v8);
          v5 = *((_DWORD *)v2 + 54);
        }
        v6 += 64LL;
        ++v7;
      }
      while ( v7 < v5 );
    }
    IOFree(*((_QWORD *)v2 + 17), (signed __int64)v5 << 6);
    *((_QWORD *)v2 + 17) = 0LL;
  }
  v9 = *((_QWORD *)v2 + 26);
  if ( v9 )
  {
    IOFree(v9, 8LL * *((_DWORD *)v2 + 54));
    *((_QWORD *)v2 + 26) = 0LL;
  }
  v10 = *((_QWORD *)v2 + 22);
  if ( v10 )
  {
    (*(void (__cdecl **)(__int64))(*(_QWORD *)v10 + 40LL))(v10);
    *((_QWORD *)v2 + 22) = 0LL;
  }
  v11 = *((_QWORD *)v2 + 24);
  if ( v11 )
  {
    IOSimpleLockFree(v11);
    *((_QWORD *)v2 + 24) = 0LL;
  }
  return (*(int (__fastcall **)(AppleAPICInterruptController *))(off_2010 + 160))(v2);
}
// 2010: using guessed type __int64 off_2010;
// A610: using guessed type int __fastcall IOFree(_QWORD, _QWORD);
// A620: using guessed type int __cdecl IOLockFree(_QWORD);
// A640: using guessed type int __cdecl IOSimpleLockFree(_QWORD);

//----- (0000000000001600) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::dumpRegisters(AppleAPICInterruptController *this)
{
  int v1; // ebx@1
  __int64 v2; // rsi@2
  signed int v3; // ebx@3
  __int64 v4; // rsi@4
  __int64 v5; // rax@4
  __int64 v6; // rcx@4
  __int64 v7; // r8@4
  int result; // eax@4

  v1 = 0;
  do
  {
    v2 = *((_DWORD *)this + 50);
    **((_DWORD **)this + 23) = v1;
    kprintf("IOAPIC-%d: reg %02x = %08x\n", v2, (unsigned int)v1++, *(_DWORD *)(*((_QWORD *)this + 23) + 16LL));
  }
  while ( v1 != 16 );
  v3 = 16;
  do
  {
    v4 = *((_DWORD *)this + 50);
    **((_DWORD **)this + 23) = v3 + 1;
    v5 = *((_QWORD *)this + 23);
    v6 = *(_DWORD *)(v5 + 16);
    *(_DWORD *)v5 = v3;
    v7 = *(_DWORD *)(*((_QWORD *)this + 23) + 16LL);
    result = kprintf("IOAPIC-%d: reg %02x = %08x %08x\n", v4, (unsigned int)v3, v6);
    v3 += 2;
  }
  while ( v3 < 64 );
  return result;
}
// AFE0: using guessed type int __fastcall kprintf(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001698) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::writeVectorEntry(AppleAPICInterruptController *this, int a2)
{
  int v2; // er14@1
  __int64 v3; // r15@1
  int v4; // er12@1
  int v5; // esi@1
  int v6; // ecx@1

  v2 = a2;
  v3 = *((_QWORD *)this + 24);
  v4 = ml_set_interrupts_enabled(0LL);
  IOSimpleLockLock(v3);
  v5 = *(_DWORD *)(*((_QWORD *)this + 26) + 8LL * a2);
  **((_DWORD **)this + 23) = 2 * v2 + 16;
  *(_DWORD *)(*((_QWORD *)this + 23) + 16LL) = v5;
  v6 = *(_DWORD *)(*((_QWORD *)this + 26) + 8LL * v2 + 4);
  **((_DWORD **)this + 23) = 2 * v2 + 17;
  *(_DWORD *)(*((_QWORD *)this + 23) + 16LL) = v6;
  IOSimpleLockUnlock(*((_QWORD *)this + 24));
  return ml_set_interrupts_enabled((unsigned int)v4);
}
// A648: using guessed type int __fastcall IOSimpleLockLock(_QWORD);
// A650: using guessed type int __fastcall IOSimpleLockUnlock(_QWORD);
// AFE8: using guessed type int __fastcall ml_set_interrupts_enabled(_QWORD);

//----- (0000000000001726) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::writeVectorEntry(__int64 a1, int a2, unsigned __int64 a3)
{
  int v3; // er13@1
  unsigned __int64 v4; // r15@1
  __int64 v5; // r12@1
  int v6; // ST04_4@1

  v3 = a3;
  v4 = a3 >> 32;
  v5 = *(_QWORD *)(a1 + 192);
  v6 = ml_set_interrupts_enabled(0LL);
  IOSimpleLockLock(v5);
  **(_DWORD **)(a1 + 184) = 2 * a2 + 16;
  *(_DWORD *)(*(_QWORD *)(a1 + 184) + 16LL) = v3;
  **(_DWORD **)(a1 + 184) = 2 * a2 + 17;
  *(_DWORD *)(*(_QWORD *)(a1 + 184) + 16LL) = v4;
  IOSimpleLockUnlock(*(_QWORD *)(a1 + 192));
  return ml_set_interrupts_enabled((unsigned int)v6);
}
// A648: using guessed type int __fastcall IOSimpleLockLock(_QWORD);
// A650: using guessed type int __fastcall IOSimpleLockUnlock(_QWORD);
// AFE8: using guessed type int __fastcall ml_set_interrupts_enabled(_QWORD);

//----- (00000000000017B2) ----------------------------------------------------
signed __int64 __fastcall AppleAPICInterruptController::getInterruptType(AppleAPICInterruptController *this, IOService *a2, int a3, int *a4)
{
  int *v4; // r14@1
  signed __int64 result; // rax@1
  signed __int64 v6; // rcx@3
  __int64 v7; // rbx@3
  int v8; // ecx@3
  __int64 v9; // rax@4

  v4 = a4;
  result = 3758097090LL;
  if ( a2 && a4 )
  {
    v6 = 16LL * a3;
    v7 = *(_QWORD *)(*((_QWORD *)a2 + 16) + v6 + 8);
    v8 = (*(int (__fastcall **)(_QWORD))(*(_QWORD *)v7 + 320LL))(*(_QWORD *)(*((_QWORD *)a2 + 16) + v6 + 8));
    result = 3758097136LL;
    if ( (unsigned int)v8 >= 8 )
    {
      LODWORD(v9) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v7 + 376LL))(v7);
      *v4 = *(_DWORD *)(v9 + 4) & 1;
      result = 0LL;
    }
  }
  return result;
}

//----- (0000000000001812) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::registerInterrupt(AppleAPICInterruptController *this, IOService *a2, unsigned int a3, void *a4, void (__cdecl *a5)(void *, void *, void *, int), void *a6)
{
  void (__cdecl *v6)(void *, void *, void *, int); // r15@1
  void *v7; // r12@1
  unsigned int v8; // er13@1
  __int64 v9; // rax@1
  int result; // eax@2
  void *v11; // [sp+0h] [bp-30h]@1

  v11 = a6;
  v6 = a5;
  v7 = a4;
  v8 = a3;
  LODWORD(v9) = (*(int (**)(void))(**(_QWORD **)(*((_QWORD *)a2 + 16) + 16LL * (signed int)a3 + 8) + 376LL))();
  if ( *(_DWORD *)v9 >= *((_DWORD *)this + 54) )
    result = -536870206;
  else
    result = (*(int (__fastcall **)(AppleAPICInterruptController *, IOService *, _QWORD, void *, void (__cdecl *)(void *, void *, void *, int), void *))(off_2010 + 2144))(
               this,
               a2,
               v8,
               v7,
               v6,
               v11);
  return result;
}
// 2010: using guessed type __int64 off_2010;

//----- (000000000000189C) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::initVector(AppleAPICInterruptController *this, int a2, __int64 a3)
{
  signed __int64 v3; // rcx@1
  __int64 v4; // rbx@1
  int result; // eax@1
  __int64 v6; // rax@2

  v3 = 16LL * *(_DWORD *)(a3 + 24);
  v4 = *(_QWORD *)(*(_QWORD *)(*(_QWORD *)(a3 + 16) + 128LL) + v3 + 8);
  result = (*(int (__fastcall **)(_QWORD))(*(_QWORD *)v4 + 320LL))(*(_QWORD *)(*(_QWORD *)(*(_QWORD *)(a3 + 16) + 128LL)
                                                                             + v3
                                                                             + 8));
  if ( (unsigned int)result >= 8 )
  {
    LODWORD(v6) = (*(int (__fastcall **)(__int64))(*(_QWORD *)v4 + 376LL))(v4);
    *(_DWORD *)(*((_QWORD *)this + 26) + 8LL * a2) = *(_DWORD *)(*((_QWORD *)this + 26) + 8LL * a2) & 0xFFFF5FFF | ((*(_DWORD *)(v6 + 4) & 1) << 15) | ((*(_DWORD *)(v6 + 4) & 2) << 12);
    result = AppleAPICInterruptController::writeVectorEntry(this, a2);
  }
  return result;
}

//----- (0000000000001928) ----------------------------------------------------
char AppleAPICInterruptController::vectorCanBeShared()
{
  return 1;
}

//----- (0000000000001930) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::getInterruptHandlerAddress(AppleAPICInterruptController *this)
{
  return *(_QWORD *)(*(_QWORD *)this + 2184LL);
}

//----- (0000000000001940) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::disableVectorHard(__int64 a1, int a2)
{
  __int64 v2; // r15@1
  int v3; // er12@1
  __int64 v4; // rcx@1
  int v5; // edx@1

  v2 = *(_QWORD *)(a1 + 192);
  v3 = ml_set_interrupts_enabled(0LL);
  IOSimpleLockLock(v2);
  v4 = *(_QWORD *)(a1 + 208);
  v5 = *(_DWORD *)(v4 + 8LL * a2) | 0x10000;
  *(_DWORD *)(v4 + 8LL * a2) = v5;
  **(_DWORD **)(a1 + 184) = 2 * a2 + 16;
  *(_DWORD *)(*(_QWORD *)(a1 + 184) + 16LL) = v5;
  IOSimpleLockUnlock(*(_QWORD *)(a1 + 192));
  return ml_set_interrupts_enabled((unsigned int)v3);
}
// A648: using guessed type int __fastcall IOSimpleLockLock(_QWORD);
// A650: using guessed type int __fastcall IOSimpleLockUnlock(_QWORD);
// AFE8: using guessed type int __fastcall ml_set_interrupts_enabled(_QWORD);

//----- (00000000000019B4) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::enableVector(__int64 a1, int a2)
{
  __int64 v2; // r15@1
  int v3; // er12@1
  __int64 v4; // rcx@1
  unsigned int v5; // edx@1

  v2 = *(_QWORD *)(a1 + 192);
  v3 = ml_set_interrupts_enabled(0LL);
  IOSimpleLockLock(v2);
  v4 = *(_QWORD *)(a1 + 208);
  v5 = *(_DWORD *)(v4 + 8LL * a2) & 0xFFFEFFFF;
  *(_DWORD *)(v4 + 8LL * a2) = v5;
  **(_DWORD **)(a1 + 184) = 2 * a2 + 16;
  *(_DWORD *)(*(_QWORD *)(a1 + 184) + 16LL) = v5;
  IOSimpleLockUnlock(*(_QWORD *)(a1 + 192));
  return ml_set_interrupts_enabled((unsigned int)v3);
}
// A648: using guessed type int __fastcall IOSimpleLockLock(_QWORD);
// A650: using guessed type int __fastcall IOSimpleLockUnlock(_QWORD);
// AFE8: using guessed type int __fastcall ml_set_interrupts_enabled(_QWORD);

//----- (0000000000001A28) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::handleInterrupt(AppleAPICInterruptController *this, void *a2, IOService *a3, unsigned int a4)
{
  int v4; // er12@1
  __int64 result; // rax@1
  __int64 v6; // r15@3
  signed __int64 v7; // rbx@5
  __int64 v8; // rbx@8
  int v9; // er15@8
  __int64 v10; // rax@8
  int v11; // ecx@8
  signed __int64 v12; // [sp+10h] [bp-30h]@5

  v4 = a4 - *((_DWORD *)this + 50);
  result = 3758097090LL;
  if ( ((a4 - *((_DWORD *)this + 50)) & 0x80000000) == 0 && v4 < *((_DWORD *)this + 54) )
  {
    v6 = *((_QWORD *)this + 17);
    if ( v6 != ~*((_QWORD *)this + 29) )
    {
      panic(
        "\"AppleAPIC: bad vectors 0x%x (%p, %p)\"@/SourceCache/AppleAPIC/AppleAPIC-17/AppleAPIC.cpp:551",
        a4,
        *((_QWORD *)this + 17),
        *((_QWORD *)this + 29));
      v6 = *((_QWORD *)this + 17);
    }
    v7 = (signed __int64)v4 << 6;
    v12 = v6 + v7;
    *(_BYTE *)(v6 + v7) = 1;
    if ( *(_BYTE *)(v6 + v7 + 1)
      || !*(_BYTE *)(v6 + v7 + 3)
      || ((*(void (__fastcall **)(_QWORD, _QWORD, _QWORD, _QWORD))(v6 + v7 + 40))(
            *(_QWORD *)(v6 + v7 + 32),
            *(_QWORD *)(v6 + v7 + 48),
            *(_QWORD *)(v6 + v7 + 16),
            *(_DWORD *)(v6 + v7 + 24)),
          *(_BYTE *)(v6 + v7 + 1)) )
    {
      *(_BYTE *)(v6 + v7 + 2) = 1;
      v8 = *((_QWORD *)this + 24);
      v9 = ml_set_interrupts_enabled(0LL);
      IOSimpleLockLock(v8);
      v10 = *((_QWORD *)this + 26);
      v11 = *(_DWORD *)(v10 + 8LL * v4) | 0x10000;
      *(_DWORD *)(v10 + 8LL * v4) = v11;
      **((_DWORD **)this + 23) = 2 * v4 + 16;
      *(_DWORD *)(*((_QWORD *)this + 23) + 16LL) = v11;
      IOSimpleLockUnlock(*((_QWORD *)this + 24));
      ml_set_interrupts_enabled((unsigned int)v9);
    }
    *(_BYTE *)v12 = 0;
    result = 0LL;
  }
  return result;
}
// A648: using guessed type int __fastcall IOSimpleLockLock(_QWORD);
// A650: using guessed type int __fastcall IOSimpleLockUnlock(_QWORD);
// AFE8: using guessed type int __fastcall ml_set_interrupts_enabled(_QWORD);

//----- (0000000000001B5E) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::prepareForSleep(AppleAPICInterruptController *this)
{
  __int64 v1; // rbx@2
  int result; // eax@3

  if ( *((_DWORD *)this + 54) > 0 )
  {
    v1 = 0LL;
    do
    {
      result = AppleAPICInterruptController::writeVectorEntry(
                 (__int64)this,
                 v1,
                 *(_DWORD *)(*((_QWORD *)this + 26) + 8 * v1) |
                 ((unsigned __int64)*(_DWORD *)(*((_QWORD *)this + 26) + 8 * v1 + 4) << 32) | 0x10000);
      ++v1;
    }
    while ( (signed int)v1 < *((_DWORD *)this + 54) );
  }
  return result;
}

//----- (0000000000001BAC) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::prepareForDeepIdle(AppleAPICInterruptController *this, int a2)
{
  int result; // eax@3

  if ( *((_DWORD *)this + 50) == 64 && *((_DWORD *)this + 54) > (unsigned int)a2 )
    result = AppleAPICInterruptController::writeVectorEntry(
               (__int64)this,
               a2,
                 ((unsigned __int64)*(_DWORD *)(*((_QWORD *)this + 26) + 8LL * (unsigned int)a2 + 4) << 32) | *(_DWORD *)(*((_QWORD *)this + 26) + 8LL * (unsigned int)a2) & 0xFFFEFFFF);
  return result;
}

//----- (0000000000001BE6) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::resumeFromSleep(AppleAPICInterruptController *this)
{
  int result; // eax@1
  __int64 v2; // rbx@2

  __outbyte(0xA1u, 0xFFu);
  __outbyte(0x21u, 0xFFu);
  result = *((_DWORD *)this + 56);
  **((_DWORD **)this + 23) = 0;
  *(_DWORD *)(*((_QWORD *)this + 23) + 16LL) = result;
  if ( *((_DWORD *)this + 54) > 0 )
  {
    v2 = 0LL;
    do
    {
      AppleAPICInterruptController::writeVectorEntry(
        (__int64)this,
        v2,
        *(_DWORD *)(*((_QWORD *)this + 26) + 8 * v2) | ((unsigned __int64)*(_DWORD *)(*((_QWORD *)this + 26) + 8 * v2 + 4) << 32) | 0x10000);
      result = AppleAPICInterruptController::writeVectorEntry(this, v2++);
    }
    while ( (signed int)v2 < *((_DWORD *)this + 54) );
  }
  return result;
}

//----- (0000000000001C64) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::setVectorPhysicalDestination(AppleAPICInterruptController *this, int a2, unsigned int a3)
{
  unsigned int v3; // er15@1
  signed int v4; // er14@1
  __int64 v5; // r12@3
  int v6; // ST04_4@3
  __int64 v7; // rax@3
  int v8; // ecx@3

  v3 = a3;
  v4 = -536870206;
  if ( *((_DWORD *)this + 54) > (unsigned int)a2 && a3 <= 0xFF )
  {
    v5 = *((_QWORD *)this + 24);
    v4 = 0;
    v6 = ml_set_interrupts_enabled(0LL);
    IOSimpleLockLock(v5);
    v7 = *((_QWORD *)this + 26);
    v8 = *(_DWORD *)(v7 + 8LL * a2) | 0x10000;
    *(_DWORD *)(v7 + 8LL * a2) = v8;
    **((_DWORD **)this + 23) = 2 * a2 + 16;
    *(_DWORD *)(*((_QWORD *)this + 23) + 16LL) = v8;
    IOSimpleLockUnlock(*((_QWORD *)this + 24));
    ml_set_interrupts_enabled((unsigned int)v6);
    *(_DWORD *)(*((_QWORD *)this + 26) + 8LL * (unsigned int)a2 + 4) = v3 << 24;
    AppleAPICInterruptController::writeVectorEntry(this, a2);
  }
  return (unsigned int)v4;
}
// A648: using guessed type int __fastcall IOSimpleLockLock(_QWORD);
// A650: using guessed type int __fastcall IOSimpleLockUnlock(_QWORD);
// AFE8: using guessed type int __fastcall ml_set_interrupts_enabled(_QWORD);

//----- (0000000000001D26) ----------------------------------------------------
int __fastcall AppleAPICInterruptController::callPlatformFunction(AppleAPICInterruptController *this, const OSSymbol *a2, unsigned __int8 a3, void *a4, void *a5, void *a6)
{
  int result; // eax@3

  if ( *((const OSSymbol **)this + 20) == a2 )
  {
    if ( (_DWORD)a4 == 2 )
    {
      AppleAPICInterruptController::prepareForDeepIdle(this, (int)a5);
    }
    else if ( (_DWORD)a4 == 1 )
    {
      AppleAPICInterruptController::prepareForSleep(this);
    }
    else if ( !(_DWORD)a4 )
    {
      AppleAPICInterruptController::resumeFromSleep(this);
    }
    result = 0;
  }
  else if ( *((const OSSymbol **)this + 21) == a2 )
  {
    result = AppleAPICInterruptController::setVectorPhysicalDestination(this, (int)a4, (unsigned int)a5);
  }
  else
  {
    result = (*(int (__fastcall **)(AppleAPICInterruptController *, const OSSymbol *, _QWORD, void *, void *, void *))(off_2010 + 1736))(
               this,
               a2,
               a3,
               a4,
               a5,
               a6);
  }
  return result;
}
// 2010: using guessed type __int64 off_2010;

//----- (0000000000001D80) ----------------------------------------------------
__int64 __fastcall AppleAPICInterruptController::MetaClass::~MetaClass(AppleAPICInterruptController::MetaClass *this)
{
  return OSMetaClass::~OSMetaClass(this);
}

//----- (0000000000001D90) ----------------------------------------------------
__int64 `global constructor keyed to'_a()
{
  __int64 result; // rax@1

  OSMetaClass::OSMetaClass(
    &AppleAPICInterruptController::gMetaClass,
    "AppleAPICInterruptController",
    off_2000[0],
    240LL);
  result = (__int64)off_2960;
  AppleAPICInterruptController::gMetaClass = off_2960;
  return result;
}
// 2000: using guessed type _QWORD off_2000[3];
// 2960: using guessed type __int64 (__fastcall *off_2960[2])(AppleAPICInterruptController::MetaClass *__hidden this);
// 2B00: using guessed type _QWORD AppleAPICInterruptController::gMetaClass;
// A698: using guessed type int __fastcall OSMetaClass::OSMetaClass(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (0000000000001DD0) ----------------------------------------------------
__int64 `global destructor keyed to'_a()
{
  return OSMetaClass::~OSMetaClass((OSMetaClass *)&AppleAPICInterruptController::gMetaClass);
}
// 2B00: using guessed type _QWORD AppleAPICInterruptController::gMetaClass;

//----- (0000000000001DE1) ----------------------------------------------------
int _start()
{
  int result; // eax@2

  if ( _realmain )
    result = _realmain();
  else
    result = 0;
  return result;
}
// 2B28: using guessed type int (*_realmain)(void);

//----- (0000000000001DFB) ----------------------------------------------------
__int64 *OSKextGetCurrentIdentifier()
{
  return &kmod_info + 2;
}
// 2A38: using guessed type __int64 kmod_info;

//----- (0000000000001E0C) ----------------------------------------------------
__int64 *OSKextGetCurrentVersionString()
{
  return &kmod_info + 10;
}
// 2A38: using guessed type __int64 kmod_info;

//----- (0000000000001E1D) ----------------------------------------------------
__int64 OSKextGetCurrentLoadTag()
{
  return *((_DWORD *)&kmod_info + 3);
}
// 2A38: using guessed type __int64 kmod_info;

//----- (0000000000001E2D) ----------------------------------------------------
int _stop()
{
  int result; // eax@2

  if ( _antimain )
    result = _antimain();
  else
    result = 0;
  return result;
}
// 2B30: using guessed type int (*_antimain)(void);

// ALL OK, 39 function(s) have been successfully decompiled
